name: Check Allowed File Names

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Check Allowed File Names:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Allowed File Names
      run: |
        NOT_SAMPLES=$(find . -not -path '*/\.*' -type f ! \( -name '*.sample' -o -name 'README.md' -o -name 'LICENSE' \))
        NOT_SAMPLES_COUNT=$(echo "${NOT_SAMPLES}" | wc -w)
        if (( NOT_SAMPLES_COUNT > 0 )); then
            echo "The following files are not allowed:"
            echo "${NOT_SAMPLES}"
            exit 1
        fi
